# Site settings
title: Pydealist
email: nathan dot cheever 12 at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Nathan Cheever is a data scientist and thinker. He sometimes writes about human purpose and living well. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pydealist.com" # the base hostname & protocol for your site
twitter_username: data_cheeves
github_username:  cheevahagadog

# Build settings
markdown: kramdown
